import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Typography,
  Box,
  Chip,
} from "@mui/material";
import ReportCard from "../common/ReportCard";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import CancelIcon from "@mui/icons-material/Cancel";
import PercentIcon from "@mui/icons-material/Percent";
import GroupsIcon from "@mui/icons-material/Groups";

const AttendanceReport = ({ data, title = "Attendance Report" }) => {
  const handleExportPDF = () => {
    console.log("Exporting PDF...");
  };

  const handleExportCSV = () => {
    console.log("Exporting CSV...");
  };

  const handlePrint = () => {
    window.print();
  };

  const totalPresent = data.filter((item) => item.status === "Present").length;
  const totalAbsent = data.filter((item) => item.status === "Absent").length;
  const attendancePercentage = (
    (totalPresent / data.length) *
    100
  ).toFixed(1);

  return (
    <ReportCard
      title={title}
      description={`Generated on ${new Date().toLocaleDateString()}`}
      onExportPDF={handleExportPDF}
      onExportCSV={handleExportCSV}
      onPrint={handlePrint}
    >
      <Box
        sx={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
          gap: 2,
          mb: 4,
        }}
      >
        <SummaryCard
          label="Present"
          value={totalPresent}
          color="success"
          icon={<CheckCircleIcon />}
        />
        <SummaryCard
          label="Absent"
          value={totalAbsent}
          color="error"
          icon={<CancelIcon />}
        />
        <SummaryCard
          label="Attendance %"
          value={`${attendancePercentage}%`}
          color="info"
          icon={<PercentIcon />}
        />
        <SummaryCard
          label="Total Students"
          value={data.length}
          color="secondary"
          icon={<GroupsIcon />}
        />
      </Box>

      <Typography variant="subtitle1" fontWeight={600} gutterBottom>
        Detailed Report
      </Typography>

      <TableContainer
        component={Paper}
        sx={{
          borderRadius: 2,
          overflow: "hidden",
          boxShadow: "0 6px 18px rgba(0,0,0,0.06)",
        }}
      >
        <Table size="small">
          <TableHead>
            <TableRow sx={{ backgroundColor: "#f5f7fb" }}>
              <TableCell>Roll No</TableCell>
              <TableCell>Student Name</TableCell>
              <TableCell align="center">Status</TableCell>
              <TableCell align="center">Date</TableCell>
              <TableCell>Remarks</TableCell>
            </TableRow>
          </TableHead>

          <TableBody>
            {data.map((row, index) => (
              <TableRow
                key={index}
                hover
                sx={{
                  "&:nth-of-type(odd)": {
                    backgroundColor: "#fafafa",
                  },
                }}
              >
                <TableCell>{row.rollNo}</TableCell>
                <TableCell>{row.name}</TableCell>
                <TableCell align="center">
                  <Chip
                    label={row.status}
                    size="small"
                    color={row.status === "Present" ? "success" : "error"}
                  />
                </TableCell>
                <TableCell align="center">{row.date}</TableCell>
                <TableCell>{row.remarks || "-"}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      <Box sx={{ display: "none", print: "block", mt: 4 }}>
        <Typography variant="body2" color="text.secondary">
          Report generated by School Management System
        </Typography>
        <Typography variant="caption" color="text.secondary">
          Page 1 of 1
        </Typography>
      </Box>
    </ReportCard>
  );
};


const SummaryCard = ({ label, value, color, icon }) => (
  <Paper
    sx={{
      p: 2.5,
      borderRadius: 2,
      display: "flex",
      alignItems: "center",
      gap: 2,
      backgroundColor: `${color}.light`,
    }}
  >
    <Box
      sx={{
        p: 1.2,
        borderRadius: "50%",
        backgroundColor: `${color}.main`,
        color: "#fff",
      }}
    >
      {icon}
    </Box>
    <Box>
      <Typography variant="h6" fontWeight={700}>
        {value}
      </Typography>
      <Typography variant="body2" color="text.secondary">
        {label}
      </Typography>
    </Box>
  </Paper>
);

export default AttendanceReport;
